# Name of parameter group:
#   node: '/ROS_node_name'
#   params:
#     param_name: 'Parameter Description'
#     ...

Roll Angle:
  node: '/autopilot'
  params:
    r_kp: 'Roll Angle P Gain'
    r_kd: 'Roll Angle D Gain'

Pitch Angle:
  node: '/autopilot'
  params:
    p_kp: 'Pitch Angle P Gain'
    p_kd: 'Pitch Angle D Gain'

Airspeed:
  node: '/autopilot'
  params:
    a_t_kp: 'Airspeed P Gain'
    a_t_ki: 'Airspeed I Gain'

Course:
  node: '/autopilot'
  params:
    c_kp: 'Course P Gain'
    c_ki: 'Course I Gain'

Altitude:
  node: '/autopilot'
  params:
    a_kp: 'Altitude P Gain'
    a_ki: 'Altitude I Gain'

Line Following:
  node: '/path_follower'
  params:
    k_path: 'Line Following P Gain'
    chi_infty: 'Line Following I Gain'

Orbit Following:
  node: '/path_follower'
  params:
    k_orbit: 'Orbit Following P Gain'
