# Name of parameter group:
#   node: '/ROS_node_name'
#   params:
#     param_name: 'Parameter Description'
#     ...

Roll Angle:
  node: '/autopilot'
  params:
    r_kp: 'Roll Angle P Gain'
    r_kd: 'Roll Angle D Gain'

Pitch Angle:
  node: '/autopilot'
  params:
    p_kp: 'Pitch Angle P Gain'
    p_kd: 'Pitch Angle D Gain'

Airspeed:
  node: '/autopilot'
  params:
    a_kp: 'Airspeed P Gain'
    a_ki: 'Airspeed I Gain'

Course:
  node: '/autopilot'
  params:
    c_kp: 'Course P Gain'
    c_ki: 'Course I Gain'

Altitude:
  node: '/autopilot'
  params:
    alt_kp: 'Altitude P Gain'
    alt_ki: 'Altitude I Gain'

Line Following:
  node: '/line_follower'
  params:
    l_kp: 'Line Following P Gain'
    l_ki: 'Line Following I Gain'

Orbit Following:
  node: '/path_follower'
  params:
    o_kp: 'Orbit Following P Gain'
    o_ki: 'Orbit Following I Gain'
    fake_param: 'Fake Param'
