# Parameters for ROSflight software-in-the-loop simulation, based on Sonicmodell Skyhunter 1800mm UAV.
# Authors: Ian Reid and Phil Tokumaru

# Mass and inertia parameters are defined in fixedwing.urdf.xacro.
# Mass: 2.28
# Jx: 0.141
# Jy: 0.208
# Jz: 0.293
# Jxz: 0.04

/fixedwing/rosflight_sil:
  ros__parameters:
    rho: 1.2682
    mass: 2.28

    wing_s: 0.4296
    wing_b: 1.795
    wing_c: 0.2276
    wing_M: 50.0
    wing_epsilon: 0.1592 # revisit -- may not need this for the calculation
    wing_alpha0: 0.05236

    D_prop : 0.2794 # prop diameter in m (11 in)
    CT_0 : 0.19720588
    CT_1 : 0.2677542
    CT_2 : -0.56626075
    CQ_0 : 0.01323475
    CQ_1 : -0.00637997
    CQ_2 : -0.01247159
    KV : 600.0        # Motor speed constant from datasheet in RPM/V
    KQ : 0.015916                       #((1 /(KV_rpm_per_volt)) *60) / (2 *M_PI) Back-emf constant, KV in V-s/rad, Motor torque constant, KQ in N-m/A
    V_max : 24.0                  # voltage for 6s battery at 4 volts per cell
    R_motor : 0.042              # ohms
    I_0 : 1.5                     # no-load (zero torque) current (A)

    servo_tau: .02

    C_L_O: .31351
    C_L_alpha: 5.1069
    C_L_beta: 0.0
    C_L_p: 0.0
    C_L_q: 8.7092
    C_L_r: 0.0
    C_L_delta_a: 0.0
    C_L_delta_e: 0.13 # Correct sign?
    C_L_delta_r: 0.0

    C_D_O: 0.00445
    C_D_alpha: 0.03 # revisit
    C_D_beta: 0.0 # revisit
    C_D_p: 0.0 # revisit
    C_D_q: 0.0 # revisit
    C_D_r: 0.0 # revisit
    C_D_delta_a: 0.0 # revisit
    C_D_delta_e: 0.0135 # revisit
    C_D_delta_r: 0.0 # revisit

    C_ell_O: 0.0
    C_ell_alpha: 0.00
    C_ell_beta: -0.0790
    C_ell_p: -0.5077
    C_ell_q: 0.0
    C_ell_r: 0.1871
    C_ell_delta_a: 0.17 #change back/double check
    C_ell_delta_e: 0.0
    C_ell_delta_r: 0.0

    C_m_O: 0.02626
    C_m_alpha: -1.2761
    C_m_beta: 0.0
    C_m_p: 0.0
    C_m_q: -17.8301 # check the sign on this
    C_m_r: 0.0
    C_m_delta_a: 0.0
    C_m_delta_e: -.99 # check the sign on this
    C_m_delta_r: 0.0

    C_n_O: 0.0
    C_n_alpha: 0.0
    C_n_beta: 0.1301
    C_n_p: -0.0364
    C_n_q: 0.0
    C_n_r: -0.1541
    C_n_delta_a: -0.011
    C_n_delta_e: 0.0
    C_n_delta_r: 0.0 #check the sign on this

    C_Y_O: 0.0
    C_Y_alpha: 0.00
    C_Y_beta: -0.3681
    C_Y_p: 0.0700
    C_Y_q: 0.0
    C_Y_r: 0.0
    C_Y_delta_a: 0.075 #check the sign on this
    C_Y_delta_e: 0.0
    C_Y_delta_r: 0.0 #check the sign on this
